[build]
builder = "nixpacks"
buildCommand = "cd functions && npm install && npm run build"

[deploy]
startCommand = "cd functions && npm start"
healthcheckPath = "/api/pastes"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 